---
- name: Generate keypairs
  ansible.builtin.include_tasks: "setup/common/generate-keypair.yml"

- name: Ensure wireguard directory exists
  become: true
  ansible.builtin.file:
    path: "/etc/wireguard"
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Wait for wireguard public key to be known on all hosts in play
  ansible.builtin.assert:
    that:
      - hostvars[item].wireguard_public_key is defined
      - hostvars[item].wireguard_public_key is string
      - hostvars[item].wireguard_public_key | length > 0
    fail_msg: "It seems like you are using a mixed environment. Please set the Ansible Play `strategy` to `free`!"
  loop: "{{ wireguard_hosts }}"
  retries: 30
  delay: 5
  register: wireguard_public_key_known
  until: wireguard_public_key_known is success

- name: Create wg0.conf
  become: true
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: "/etc/wireguard/{{ wireguard_interface_name }}.conf"
    owner: root
    group: root
    mode: '0600'
  notify: Restart wireguard
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags" # Rotating keys

- name: Set necessary sysctl values
  become: true
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/99-wireguard.conf
  loop:
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'net.ipv6.conf.all.forwarding', value: '1' }
    - { name: 'net.ipv4.conf.all.send_redirects', value: '0' }
  register: sysctl_reload
  failed_when: "sysctl_reload is failed and 'molecule-notest' not in ansible_skip_tags" # Systemd user units don't work in docker

- name: Enable wireguard
  become: true
  ansible.builtin.service:
    name: 'wg-quick@{{ wireguard_interface_name }}'
    state: "started"
    enabled: true

...
