---
- name: "Main | include setup specific tasks"
  ansible.builtin.set_fact:
    _wireguard_agent_setup_file: "{{ lookup('ansible.builtin.first_found', find_plays) }}"
  vars:
    find_plays:
      files:
        - "{{ ansible_facts.distribution | lower }}-{{ ansible_facts.distribution_version | lower }}.yml"
        - "{{ ansible_facts.distribution | lower }}-{{ ansible_facts.distribution_major_version | lower }}.yml"
        - "{{ ansible_facts.distribution | lower }}.yml"
        - "{{ ansible_facts.os_family | lower }}.yml"
        - "{{ ansible_facts.system | lower }}.yml"
        - "main.yml"
      paths:
        - "setup"

- name: "Main | include tasks for wireguard"
  ansible.builtin.include_tasks: "{{ _wireguard_agent_setup_file }}"
  when: _wireguard_agent_setup_file is defined
...
