---
- name: "Reboot host"
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 600
    test_command: /usr/bin/true
    pre_reboot_delay: 5
    post_reboot_delay: 5

- name: Restart wireguard
  become: true
  ansible.builtin.service:
    name: 'wg-quick@{{ wireguard_interface_name }}'
    state: "restarted"
    enabled: true
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags" # Rotating keys

...
