---
- name: Restart wireguard
  become: true
  ansible.builtin.service:
    name: 'wg-quick@{{ wireguard_interface_name }}'
    state: "restarted"
    enabled: true
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags" # Rotating keys

...
