---
- name: "Setup | Generate private"
  ansible.builtin.shell: |
    wg genkey
  register: wireguard_private_key_output
  when: wireguard_private_key is not defined
  changed_when: false

- name: "Setup | Set variable to plain value"
  ansible.builtin.set_fact:
    wireguard_private_key: "{{ wireguard_private_key_output.stdout_lines[0] }}"
  when: wireguard_private_key_output.changed
  changed_when: false

- name: "Setup | Generate public"
  ansible.builtin.shell: |
    echo {{ wireguard_private_key }} | wg pubkey
  register: wireguard_public_key_output
  when: wireguard_public_key is not defined
  changed_when: false

- name: "Setup | Set variable to plain value"
  ansible.builtin.set_fact:
    wireguard_public_key: "{{ wireguard_public_key_output.stdout_lines[0] }}"
  when: wireguard_public_key_output.changed
  changed_when: false

...
