---
- name: "Setup | Include keypair tasks"
  ansible.builtin.include_tasks: generate-keypair.yml

- name: "Setup | Ensure wireguard directory exists"
  become: true
  ansible.builtin.file:
    path: "/etc/wireguard"
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: "Setup | Create wg0.conf"
  become: true
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: "/etc/wireguard/{{ wireguard_interface_name }}.conf"
    owner: root
    group: root
    mode: '0600'
  register: wireguard_config

- name: Set necessary sysctl values
  become: true
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/99-wireguard.conf
  loop:
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'net.ipv6.conf.all.forwarding', value: '1' }
    - { name: 'net.ipv4.conf.all.send_redirects', value: '0' }

- name: "Setup | Enable wireguard"
  become: true
  ansible.builtin.service:
    name: 'wg-quick@{{ wireguard_interface_name }}'
    state: "{% if wireguard_config.changed %}restarted{% else %}started{% endif %}"
    enabled: true
...
